export const scenarios = [
  {
    id: "weather",
    title: "The Weather",
    portugueseTitle: "O Tempo",
    icon: "🌦️",
    roleplay: "Conversing with a neighbor about the daily forecast.",
    keywords: [
      { word: "Sol", en: "The sun is very strong.", ex: "O sol está muito forte." },
      { word: "Chuva", en: "I like the sound of the rain.", ex: "Eu gosto do som da chuva." },
      { word: "Vento", en: "The wind is blowing.", ex: "O vento está a soprar." },
      { word: "Nuvens", en: "The sky has many clouds.", ex: "O céu tem muitas nuvens." },
      { word: "Frio", en: "It is very cold outside.", ex: "Está muito frio lá fora." },
      { word: "Calor", en: "I don't like this heat.", ex: "Não gosto deste calor." },
      { word: "Nevoeiro", en: "There is a lot of fog on the road.", ex: "Há muito nevoeiro na estrada." },
      { word: "Trovoada", en: "I am afraid of the thunderstorm.", ex: "Tenho medo da trovoada." },
      { word: "Temperatura", en: "The temperature is going to rise.", ex: "A temperatura vai subir." },
      { word: "Graus", en: "It's twenty degrees now.", ex: "Estão vinte graus agora." },
      { word: "Arco-íris", en: "Look at the rainbow!", ex: "Olha para o arco-íris!" },
      { word: "Guarda-chuva", en: "I took my umbrella.", ex: "Levei o meu guarda-chuva." },
      { word: "Aquecimento", en: "Turn on the heating, please.", ex: "Liga o aquecimento, por favor." },
      { word: "Casaco", en: "Do you need a coat?", ex: "Precisas de um casaco?" },
      { word: "Neve", en: "I have never seen snow in Lisbon.", ex: "Nunca vi neve em Lisboa." },
      { word: "Nublado", en: "The weather is cloudy.", ex: "O tempo está nublado." },
      { word: "Inverno", en: "The winter is very humid.", ex: "O inverno é muito húmido." },
      { word: "Verão", en: "I love the summer in Portugal.", ex: "Adoro o verão em Portugal." },
      { word: "Primavera", en: "The flowers open in the spring.", ex: "As flores abrem na primavera." },
      { word: "Outono", en: "The leaves fall in the autumn.", ex: "As folhas caem no outono." },
      { word: "Humidade", en: "The humidity is high today.", ex: "A humidade está alta hoje." },
      { word: "Geada", en: "There was frost on the lawn.", ex: "Havia geada no relvado." },
      { word: "Relâmpago", en: "I saw a lightning flash in the sky.", ex: "Vi um relâmpago no céu." },
      { word: "Sombra", en: "Let's go into the shade.", ex: "Vamos para a sombra." },
      { word: "Previsão", en: "What is the weather forecast?", ex: "Qual é a previsão do tempo?" },
      { word: "Gelado", en: "My coffee is ice-cold.", ex: "O meu café está gelado." },
      { word: "Abafado", en: "The air is very stuffy.", ex: "O ar está muito abafado." },
      { word: "Ventoinha", en: "Turn on the fan.", ex: "Liga a ventoinha." },
      { word: "Tromba d'água", en: "A cloudburst fell.", ex: "Caiu uma tromba d'água." },
      { word: "Céu", en: "The sky is blue.", ex: "O céu está azul." }
    ]
  },
  {
    id: "greetings",
    title: "Greetings & Small Talk",
    portugueseTitle: "Cumprimentos",
    icon: "🤝",
    roleplay: "Meeting a new person and starting a basic conversation.",
    keywords: [
      { word: "Olá", en: "Hello! How are you?", ex: "Olá! Como estás?" },
      { word: "Bom dia", en: "Good morning to everyone!", ex: "Bom dia a todos!" },
      { word: "Boa tarde", en: "Good afternoon, Mr. Silva.", ex: "Boa tarde, senhor Silva." },
      { word: "Boa noite", en: "Good night and sweet dreams.", ex: "Boa noite e bons sonhos." },
      { word: "Como estás?", en: "Hello, how are you today?", ex: "Olá, como estás hoje?" },
      { word: "Tudo bem?", en: "Everything is well here.", ex: "Tudo bem por aqui." },
      { word: "Prazer", en: "Pleasure to meet you.", ex: "Muito prazer em conhecer-te." },
      { word: "Até logo", en: "I have to go, see you later!", ex: "Tenho de ir, até logo!" },
      { word: "Tchau", en: "Bye! See you tomorrow.", ex: "Tchau! Vemo-nos amanhã." },
      { word: "Adeus", en: "Goodbye and have a good trip.", ex: "Adeus e boa viagem." },
      { word: "Obrigado", en: "Thank you very much for the help.", ex: "Muito obrigado pela ajuda." },
      { word: "De nada", en: "You're welcome, it was a pleasure.", ex: "De nada, foi um prazer." },
      { word: "Desculpa", en: "Sorry for the delay.", ex: "Desculpa o atraso." },
      { word: "Com licença", en: "Excuse me, can I pass?", ex: "Com licença, posso passar?" },
      { word: "Por favor", en: "A coffee, please.", ex: "Um café, por favor." },
      { word: "Chamo-me", en: "My name is Pedro, and you?", ex: "Chamo-me Pedro, e tu?" },
      { word: "Nome", en: "What is your name?", ex: "Qual é o teu nome?" },
      { word: "Sou de", en: "I am from Portugal.", ex: "Sou de Portugal." },
      { word: "Onde vives?", en: "Where do you live now?", ex: "Onde vives agora?" },
      { word: "Quantos anos?", en: "How many years old are you?", ex: "Quantos anos tens?" },
      { word: "Trabalho", en: "Where is your workplace?", ex: "Onde é o teu trabalho?" },
      { word: "Estudo", en: "I study Portuguese.", ex: "Eu estudo português." },
      { word: "Sim", en: "Yes, I want to go.", ex: "Sim, eu quero ir." },
      { word: "Não", en: "No, thank you.", ex: "Não, obrigado." },
      { word: "Talvez", en: "Maybe I will go tomorrow.", ex: "Talvez eu vá amanhã." },
      { word: "Percebo", en: "Yes, I understand well.", ex: "Sim, eu percebo bem." },
      { word: "Repetir", en: "Can you repeat, please?", ex: "Podes repetir, por favor?" },
      { word: "Devagar", en: "Speak more slowly.", ex: "Fala mais devagar." },
      { word: "Ajuda", en: "I need help here.", ex: "Preciso de ajuda aqui." },
      { word: "Amigo", en: "He is my best friend.", ex: "Ele é o meu melhor amigo." }
    ]
  },
  {
    id: "connectors",
    title: "Connecting Words",
    portugueseTitle: "Conectores",
    icon: "🔗",
    roleplay: "Linking ideas to make your sentences flow more naturally.",
    keywords: [
      { word: "E", en: "I like coffee and tea.", ex: "Gosto de café e chá." },
      { word: "Mas", en: "I want to go, but I can't.", ex: "Quero ir, mas não posso." },
      { word: "Ou", en: "Do you want this or that?", ex: "Queres isto ou aquilo?" },
      { word: "Porque", en: "I study because I like it.", ex: "Estudo porque gosto." },
      { word: "Por isso", en: "It was cold, therefore I stayed.", ex: "Estava frio, por isso fiquei." },
      { word: "Também", en: "I also want to go.", ex: "Eu também quero ir." },
      { word: "Embora", en: "I'm going, although I'm tired.", ex: "Vou, embora esteja cansado." },
      { word: "Apesar de", en: "We went out despite the rain.", ex: "Saímos apesar da chuva." },
      { word: "Se", en: "If it rains, I won't go.", ex: "Se chover, não vou." },
      { word: "Quando", en: "Tell me when you arrive.", ex: "Diz-me quando chegares." },
      { word: "Enquanto", en: "Read while you wait.", ex: "Lê enquanto esperas." },
      { word: "Antes de", en: "Wash your hands before eating.", ex: "Lava as mãos antes de comer." },
      { word: "Depois de", en: "I'm going to have dinner after running.", ex: "Vou jantar depois de correr." },
      { word: "Durante", en: "I slept during the movie.", ex: "Dormi durante o filme." },
      { word: "Além disso", en: "It is cheap, besides it is good.", ex: "É barato, além disso é bom." },
      { word: "Então", en: "So, what did you decide?", ex: "Então, o que decidiste?" },
      { word: "Portanto", en: "I studied, so I passed.", ex: "Estudei, portanto passei." },
      { word: "Contudo", en: "He tried, however he failed.", ex: "Tentou, contudo falhou." },
      { word: "Todavia", en: "It is difficult, nevertheless possible.", ex: "É difícil, todavia possível." },
      { word: "Pois", en: "I didn't go, for I was sick.", ex: "Não fui, pois estava doente." },
      { word: "Assim", en: "Do it like this, with care.", ex: "Faz assim, com cuidado." },
      { word: "Caso", en: "Take the coat, in case it gets cold.", ex: "Leva o casaco, caso faça frio." },
      { word: "Já que", en: "Since you are here, help me.", ex: "Já que estás aqui, ajuda-me." },
      { word: "Para que", en: "I spoke loudly so that they would hear.", ex: "Falei alto para que ouvissem." },
      { word: "Ainda que", en: "I'm going, even though it's late.", ex: "Vou, ainda que seja tarde." },
      { word: "Até", en: "I stay here until five.", ex: "Fico aqui até às cinco." },
      { word: "Exceto", en: "Everyone went, except João.", ex: "Todos foram, exceto o João." },
      { word: "Salvo", en: "Everything is fine, except the TV.", ex: "Está tudo bem, salvo a TV." },
      { word: "Contanto que", en: "I'm going, provided that you pay.", ex: "Vou, contanto que pagues." },
      { word: "Afinal", en: "After all, I was right.", ex: "Afinal, eu tinha razão." }
    ]
  },
  {
    id: "alphabet",
    title: "Alphabet & Accents",
    portugueseTitle: "O Alfabeto",
    icon: "🔤",
    roleplay: "Practicing the unique sounds and accents of European Portuguese.",
    keywords: [
      { word: "A", en: "Friend starts with A.", ex: "Amigo começa com A." },
      { word: "B", en: "B as in ball.", ex: "B de bola." },
      { word: "C", en: "House is written with C.", ex: "Casa escreve-se com C." },
      { word: "Ç", en: "Apple has a cedilla.", ex: "Maçã tem uma cedilha." },
      { word: "Á", en: "Water has an acute accent.", ex: "Água tem acento agudo." },
      { word: "À", en: "I am going to school.", ex: "Vou à escola." },
      { word: "Â", en: "Lamp has a circumflex.", ex: "Lâmpada tem circunflexo." },
      { word: "Ã", en: "Dog ends in a tilde.", ex: "Cão termina em til." },
      { word: "D", en: "D as in dice.", ex: "D de dado." },
      { word: "E", en: "School with E.", ex: "Escola com E." },
      { word: "F", en: "F as in knife.", ex: "F de faca." },
      { word: "G", en: "G as in cat.", ex: "G de gato." },
      { word: "H", en: "H as in today.", ex: "H de hoje." },
      { word: "I", en: "I as in island.", ex: "I de ilha." },
      { word: "J", en: "J as in window.", ex: "J de janela." },
      { word: "K", en: "K as in kilo.", ex: "K de kilo." },
      { word: "L", en: "L as in book.", ex: "L de livro." },
      { word: "M", en: "M as in sea.", ex: "M de mar." },
      { word: "N", en: "N as in ship.", ex: "N de navio." },
      { word: "O", en: "O as in egg.", ex: "O de ovo." },
      { word: "P", en: "P as in father.", ex: "P de pai." },
      { word: "Q", en: "Q as in cheese.", ex: "Q de queijo." },
      { word: "R", en: "R as in rat.", ex: "R de rato." },
      { word: "S", en: "S as in sun.", ex: "S de sol." },
      { word: "T", en: "T as in earth.", ex: "T de terra." },
      { word: "U", en: "U as in grape.", ex: "U de uva." },
      { word: "V", en: "V as in wind.", ex: "V de vento." },
      { word: "W", en: "W as in web.", ex: "W de web." },
      { word: "X", en: "X as in teacup.", ex: "X de xícara." },
      { word: "Z", en: "Z as in zebra.", ex: "Z de zebra." }
    ]
  },
  {
    id: "questions",
    title: "Who, What, Where?",
    portugueseTitle: "Interrogações",
    icon: "❓",
    roleplay: "Asking questions to find information and navigate daily life.",
    keywords: [
      { word: "Quem", en: "Who is that lady?", ex: "Quem é aquela senhora?" },
      { word: "O quê", en: "What is it that you said?", ex: "O que é que disseste?" },
      { word: "Quando", en: "When is your dinner?", ex: "Quando é o teu jantar?" },
      { word: "Onde", en: "Where is the key?", ex: "Onde está a chave?" },
      { word: "Porque", en: "Why are you sad?", ex: "Porque estás triste?" },
      { word: "Como", en: "How do you say this?", ex: "Como se diz isto?" },
      { word: "Qual", en: "Which is your favorite?", ex: "Qual é o teu favorito?" },
      { word: "Quanto", en: "How much does the ticket cost?", ex: "Quanto custa o bilhete?" },
      { word: "Quantos", en: "How many books did you read?", ex: "Quantos livros leste?" },
      { word: "Porquê", en: "I don't know why.", ex: "Não sei porquê." },
      { word: "Aonde", en: "Where are you going now?", ex: "Aonde vais agora?" },
      { word: "De onde", en: "Where are you coming from?", ex: "De onde vens?" },
      { word: "De quem", en: "Whose car is this?", ex: "De quem é este carro?" },
      { word: "Com quem", en: "With whom are you going out?", ex: "Com quem vais sair?" },
      { word: "Para quem", en: "For whom is the present?", ex: "Para quem é o presente?" },
      { word: "Para onde", en: "Where are you looking to?", ex: "Para onde olhas?" },
      { word: "A que horas", en: "At what time does it start?", ex: "A que horas começa?" },
      { word: "Com frequência", en: "How often do you run?", ex: "Com que frequência corres?" },
      { word: "Que tipo", en: "What type of music do you like?", ex: "Que tipo de música gostas?" },
      { word: "Qual deles", en: "Which of them do you want?", ex: "Qual deles queres?" },
      { word: "De que maneira", en: "In what way did you do it?", ex: "De que maneira fizeste?" },
      { word: "Desde quando", en: "Since when have you been here?", ex: "Desde quando estás aqui?" },
      { word: "Até quando", en: "Until when are you staying?", ex: "Ficas até quando?" },
      { word: "Há quanto tempo", en: "For how long have you been waiting?", ex: "Há quanto tempo esperas?" },
      { word: "Distância", en: "At what distance is the coffee shop?", ex: "A que distância fica o café?" },
      { word: "Sobre o quê", en: "What were they talking about?", ex: "Sobre o que falavam?" },
      { word: "Com quê", en: "With what did you open the door?", ex: "Com que abriste a porta?" },
      { word: "Dúvida", en: "Do you have any doubt?", ex: "Tens alguma dúvida?" },
      { word: "Resposta", en: "I don't know the answer.", ex: "Não sei a resposta." },
      { word: "Pergunta", en: "I asked a difficult question.", ex: "Fiz uma pergunta difícil." }
    ]
  },
  {
    id: "directions",
    title: "Directions",
    portugueseTitle: "Direções",
    icon: "🗺️",
    roleplay: "Navigating through the streets of a Portuguese city.",
    keywords: [
      { word: "Esquerda", en: "Turn to the left.", ex: "Vira à esquerda." },
      { word: "Direita", en: "It is on your right.", ex: "Fica à tua direita." },
      { word: "Em frente", en: "Go always straight ahead.", ex: "Segue sempre em frente." },
      { word: "Atrás", en: "The car is behind.", ex: "O carro está atrás." },
      { word: "Ao lado de", en: "I live next to the school.", ex: "Moro ao lado da escola." },
      { word: "Entre", en: "It is between the bank and the coffee shop.", ex: "Fica entre o banco e o café." },
      { word: "Esquina", en: "See you at the corner.", ex: "Vemo-nos na esquina." },
      { word: "Rua", en: "This street is very narrow.", ex: "Esta rua é muito estreita." },
      { word: "Avenida", en: "The avenue is wide.", ex: "A avenida é larga." },
      { word: "Praça", en: "The central square is beautiful.", ex: "A praça central é linda." },
      { word: "Ponte", en: "Cross the bridge.", ex: "Atravessa a ponte." },
      { word: "Rotunda", en: "Take the third exit.", ex: "Sai na terceira saída." },
      { word: "Semáforo", en: "Stop at the traffic light.", ex: "Para no semáforo." },
      { word: "Passadeira", en: "Cross at the crosswalk.", ex: "Atravessa na passadeira." },
      { word: "Mapa", en: "I am looking at the map.", ex: "Estou a olhar para o mapa." },
      { word: "GPS", en: "The GPS says to turn.", ex: "O GPS diz para virar." },
      { word: "Norte", en: "Porto is in the north.", ex: "O Porto fica no norte." },
      { word: "Sul", en: "The Algarve is in the south.", ex: "O Algarve fica no sul." },
      { word: "Perto", en: "It is very near here.", ex: "Fica muito perto daqui." },
      { word: "Longe", en: "The beach is far away.", ex: "A praia está longe." },
      { word: "Subir", en: "You have to go up the hill.", ex: "Tens de subir a colina." },
      { word: "Descer", en: "Go down the stairs.", ex: "Desce as escadas." },
      { word: "Virar", en: "Turn at the next street.", ex: "Vira na próxima rua." },
      { word: "Atravessar", en: "Cross the river.", ex: "Atravessa o rio." },
      { word: "Localizar", en: "I can't locate the store.", ex: "Não consigo localizar a loja." },
      { word: "Sinal", en: "Follow the traffic sign.", ex: "Segue o sinal de trânsito." },
      { word: "Distância", en: "The distance is short.", ex: "A distância é curta." },
      { word: "Chegar", en: "I want to arrive quickly.", ex: "Quero chegar depressa." },
      { word: "Partir", en: "The train is going to leave.", ex: "O comboio vai partir." },
      { word: "Destino", en: "What is your destination?", ex: "Qual é o teu destino?" }
    ]
  },
  {
    id: "prepositions",
    title: "Prepositions",
    portugueseTitle: "Preposições",
    icon: "📍",
    roleplay: "Defining where objects are located in space.",
    keywords: [
      { word: "Em cima de", en: "The book is on top of the table.", ex: "O livro está em cima de mesa." },
      { word: "Debaixo de", en: "The keys fell under the sofa.", ex: "As chaves caíram debaixo do sofá." },
      { word: "Dentro de", en: "The milk is inside the refrigerator.", ex: "O leite está dentro do frigorífico." },
      { word: "Fora de", en: "She is outside the house.", ex: "Ela está fora de casa." },
      { word: "À frente de", en: "Wait for me in front of the cinema.", ex: "Espera-me à frente do cinema." },
      { word: "Atrás de", en: "The garden is behind the house.", ex: "O jardim fica atrás da casa." },
      { word: "Perto de", en: "I live near you.", ex: "Moro perto de ti." },
      { word: "Longe de", en: "The city is far from the sea.", ex: "A cidade está longe de mar." },
      { word: "Entre", en: "Sit between us.", ex: "Senta-te entre nós." },
      { word: "Ao lado de", en: "It is next to the bank.", ex: "Fica ao lado do banco." },
      { word: "Por cima de", en: "The plane flies over the clouds.", ex: "O avião voa por cima de nuvens." },
      { word: "Por baixo de", en: "The fish swims below the water.", ex: "O peixe nada por baixo de água." },
      { word: "Através de", en: "Look through the window.", ex: "Olha através da janela." },
      { word: "Contra", en: "Lean against the wall.", ex: "Encosta-te contra a parede." },
      { word: "Sem", en: "I don't live without coffee.", ex: "Não vivo sem café." },
      { word: "Com", en: "I am going with my friends.", ex: "Vou com os meus amigos." },
      { word: "Para", en: "This present is for you.", ex: "Este presente é para ti." },
      { word: "Por", en: "I'm going by that way.", ex: "Vou por aquele caminho." },
      { word: "De", en: "I am from Lisbon.", ex: "Sou de Lisboa." },
      { word: "Em", en: "I am at home.", ex: "Estou em casa." },
      { word: "Desde", en: "I have been working since eight.", ex: "Trabalho desde as oito." },
      { word: "Até", en: "Until tomorrow!", ex: "Até amanhã!" },
      { word: "Passado", en: "He passed by me.", ex: "Passou por mim." },
      { word: "Do outro lado", en: "I live on the other side of the street.", ex: "Moro do outro lado da rua." },
      { word: "Em direção a", en: "Walk towards the light.", ex: "Caminha em direção à luz." },
      { word: "Entre", en: "He was among the crowd.", ex: "Ele estava entre a multidão." },
      { word: "Acima de", en: "It is above expectations.", ex: "Fica acima das expectativas." },
      { word: "Perante", en: "He appeared before the judge.", ex: "Compareceu perante o juiz." },
      { word: "Segundo", en: "According to the news, it is going to rain.", ex: "Segundo as notícias, vai chover." },
      { word: "Sob", en: "We are under pressure.", ex: "Estamos sob pressão." }
    ]
  },
  {
    id: "phrases",
    title: "Useful Phrases",
    portugueseTitle: "Expressões",
    icon: "✨",
    roleplay: "Common idiomatic expressions to sound like a local.",
    keywords: [
      { word: "Claro", en: "Of course yes!", ex: "Claro que sim!" },
      { word: "Certeza", en: "Are you sure?", ex: "Tens a certeza?" },
      { word: "Acho que", en: "I think that it is going to rain.", ex: "Acho que vai chover." },
      { word: "Pois é", en: "That's right, you are right.", ex: "Pois é, tens razão." },
      { word: "Verdade", en: "It's true, it was me.", ex: "É verdade, fui eu." },
      { word: "Exato", en: "Exactly what I said.", ex: "Exatamente o que eu disse." },
      { word: "Pelos vistos", en: "Apparently, he won.", ex: "Pelos vistos, ele ganhou." },
      { word: "Quem sabe?", en: "Maybe so, who knows?", ex: "Talvez sim, quem sabe?" },
      { word: "Oxalá!", en: "Hopefully everything goes well.", ex: "Oxalá que corra tudo bem." },
      { word: "Paciência", en: "It is necessary to have patience.", ex: "É preciso ter paciência." },
      { word: "Não faz mal", en: "It doesn't matter, I will help.", ex: "Não faz mal, eu ajudo." },
      { word: "Chatice", en: "What a bummer, I lost the bus.", ex: "Que chatice, perdi o autocarro." },
      { word: "Fixe", en: "This place is very cool!", ex: "Este sítio é bué da fixe!" },
      { word: "A sério?", en: "You won? Seriously?", ex: "Ganhaste? A sério?" },
      { word: "Já agora", en: "By the way, what is your name?", ex: "Já agora, como se chama?" },
      { word: "No fundo", en: "In the end, he is good.", ex: "No fundo, ele é bom." },
      { word: "Afinal", en: "After all, you arrived on time.", ex: "Afinal, chegaste a horas." },
      { word: "Mesmo", en: "Seriously? Really?", ex: "A sério? Mesmo?" },
      { word: "Pois", en: "Yeah, I understand.", ex: "Pois, eu compreendo." },
      { word: "Olhe lá", en: "Look here, can you help me?", ex: "Olhe lá, pode ajudar-me?" },
      { word: "Gozar", en: "Are you joking with me?", ex: "Estás a gozar comigo?" },
      { word: "Tomara!", en: "I wish/hope that we win.", ex: "Tomara que ganhemos." },
      { word: "Visto que", en: "Given that it is late, I'm going away.", ex: "Visto que é tarde, vou-me embora." },
      { word: "De qualquer forma", en: "I'm going anyway.", ex: "Vou de qualquer forma." },
      { word: "Enfim", en: "Oh well, the day is over.", ex: "Enfim, terminou o dia." },
      { word: "Ainda bem", en: "Good thing that you came.", ex: "Ainda bem que vieste." },
      { word: "Dá cá", en: "Give me that book.", ex: "Dá cá esse livro." },
      { word: "Deixa lá", en: "Never mind, don't worry.", ex: "Deixa lá, não te preocupes." },
      { word: "Vá lá", en: "Come on, help your friends.", ex: "Vá lá, ajuda os teus amigos." },
      { word: "Olha", en: "Look at that castle.", ex: "Olha para aquele castelo." }
    ]
  },
  {
    id: "family",
    title: "Family",
    portugueseTitle: "A Família",
    icon: "👨‍👩‍👧‍👦",
    roleplay: "Talking about your relatives and family history.",
    keywords: [
      { word: "Mãe", en: "My mother is a doctor.", ex: "A minha mãe é médica." },
      { word: "Pai", en: "My father likes to cook.", ex: "O meu pai gosta de cozinhar." },
      { word: "Irmão", en: "My brother travels a lot.", ex: "O meu irmão viaja muito." },
      { word: "Irmã", en: "My sister studies arts.", ex: "A minha irmã estuda artes." },
      { word: "Avó", en: "My grandmother makes cakes.", ex: "A minha avó faz bolos." },
      { word: "Avô", en: "My grandfather tells stories.", ex: "O meu avô conta histórias." },
      { word: "Filho", en: "My son is five years old.", ex: "O meu filho tem cinco anos." },
      { word: "Filha", en: "My daughter plays tennis.", ex: "A minha filha joga ténis." },
      { word: "Tio", en: "My uncle lives in the Algarve.", ex: "O meu tio vive no Algarve." },
      { word: "Tia", en: "My aunt is a teacher.", ex: "A minha tia é professora." },
      { word: "Primo", en: "My cousin is coming for dinner.", ex: "O meu primo vem jantar." },
      { word: "Prima", en: "My cousin is friendly.", ex: "A minha prima é simpática." },
      { word: "Neto", en: "My grandson is very tall.", ex: "O meu neto é muito alto." },
      { word: "Marido", en: "My husband is at work.", ex: "O meu marido está no trabalho." },
      { word: "Esposa", en: "My wife speaks English.", ex: "A minha esposa fala inglês." },
      { word: "Sogro", en: "My father-in-law is retired.", ex: "O meu sogro é reformado." },
      { word: "Nora", en: "My daughter-in-law is a lawyer.", ex: "A minha nora é advogada." },
      { word: "Gémeos", en: "They are twins.", ex: "Eles são gémeos." },
      { word: "Bebé", en: "The baby is sleeping.", ex: "O bebé está a dormir." },
      { word: "Criança", en: "The child is playing.", ex: "A criança está a brincar." }
    ]
  },
  {
    id: "diy-store",
    title: "At the DIY Store",
    portugueseTitle: "No Aki / Leroy Merlin",
    icon: "🛠️",
    roleplay: "Asking for tools at a Portuguese home improvement store.",
    keywords: [
      { word: "Martelo", en: "Where is the hammer?", ex: "Onde está o martelo?" },
      { word: "Prego", en: "I need a nail.", ex: "Preciso de um prego." },
      { word: "Serra", en: "This saw is very sharp.", ex: "Esta serra é muito afiada." },
      { word: "Parafuso", en: "The screw is loose.", ex: "O parafuso está solto." },
      { word: "Berbequim", en: "The drill makes noise.", ex: "O berbequim faz barulho." },
      { word: "Tinta", en: "I chose the white paint.", ex: "Escolhi a tinta branca." },
      { word: "Pincel", en: "Wash the brush after using.", ex: "Pincel lava o pincel depois de usar." },
      { word: "Madeira", en: "This wood is oak.", ex: "Esta madeira é de carvalho." },
      { word: "Cano", en: "The pipe is clogged.", ex: "O cano está entupido." },
      { word: "Lâmpada", en: "The bulb has blown.", ex: "A lâmpada fundiu." }
    ]
  },
  {
    id: "hobbies",
    title: "Hobbies",
    portugueseTitle: "Passatempos",
    icon: "🎸",
    roleplay: "Discussing what you do for fun in your leisure time.",
    keywords: [
      { word: "Musica", en: "I listen to relaxing music.", ex: "Eu oiço música relaxante." },
      { word: "Leitura", en: "Reading opens horizons.", ex: "A leitura abre horizontes." },
      { word: "Viagem", en: "An unforgettable trip.", ex: "Uma viagem inesquecível." },
      { word: "Cozinha", en: "Cooking is my passion.", ex: "A cozinha é a minha paixão." },
      { word: "Fotografia", en: "I love taking photographs.", ex: "Adoro tirar fotografias." },
      { word: "Corrida", en: "Running gives me energy.", ex: "A corrida dá-me energia." },
      { word: "Guitarra", en: "My guitar is new.", ex: "A minha guitarra é nova." },
      { word: "Dança", en: "Dance is liberating.", ex: "A dança é libertadora." },
      { word: "Yoga", en: "Yoga brings peace.", ex: "O yoga traz paz." },
      { word: "Pesca", en: "Fishing requires silence.", ex: "A pesca exige silêncio." }
    ]
  }
];
