export const scenarios = [
  {
    id: "weather",
    title: "The Weather",
    portugueseTitle: "O Tempo",
    icon: "🌦️",
    phrases: [{ pt: "Está sol.", en: "It is sunny." }],
    roleplay: "Conversing with a neighbor about the daily forecast.",
    keywords: [
      { word: "Sol", en: "Sun", ex: "O sol está muito forte." },
      { word: "Chuva", en: "Rain", ex: "Eu gosto do som da chuva." },
      { word: "Vento", en: "Wind", ex: "O vento está a soprar." },
      { word: "Nuvens", en: "Clouds", ex: "O céu tem muitas nuvens." },
      { word: "Frio", ex: "Está muito frio lá fora.", en: "Cold" },
      { word: "Calor", ex: "Não gosto deste calor.", en: "Heat" },
      { word: "Nevoeiro", ex: "Há muito nevoeiro na estrada.", en: "Fog" },
      { word: "Trovoada", ex: "Tenho medo da trovoada.", en: "Thunderstorm" },
      { word: "Temperatura", ex: "A temperatura vai subir.", en: "Temperature" },
      { word: "Graus", ex: "Estão vinte graus agora.", en: "Degrees" },
      { word: "Arco-íris", ex: "Olha para o arco-íris!", en: "Rainbow" },
      { word: "Guarda-chuva", ex: "Levei o meu guarda-chuva.", en: "Umbrella" },
      { word: "Aquecimento", ex: "Liga o aquecimento, por favor.", en: "Heating" },
      { word: "Casaco", ex: "Precisas de um casaco?", en: "Coat" },
      { word: "Neve", ex: "Nunca vi neve em Lisboa.", en: "Snow" },
      { word: "Nublado", ex: "O tempo está nublado.", en: "Cloudy" },
      { word: "Inverno", ex: "O inverno é muito húmido.", en: "Winter" },
      { word: "Verão", ex: "Adoro o verão em Portugal.", en: "Summer" },
      { word: "Primavera", ex: "As flores abrem na primavera.", en: "Spring" },
      { word: "Outono", ex: "As folhas caem no outono.", en: "Autumn" },
      { word: "Humidade", ex: "A humidade está alta hoje.", en: "Humidity" },
      { word: "Geada", ex: "Havia geada no relvado.", en: "Frost" },
      { word: "Relâmpago", ex: "Vi um relâmpago no céu.", en: "Lightning" },
      { word: "Sombra", ex: "Vamos para a sombra.", en: "Shadow/Shade" },
      { word: "Previsão", ex: "Qual é a previsão do tempo?", en: "Forecast" },
      { word: "Gelado", ex: "O meu café está gelado.", en: "Icy/Frozen" },
      { word: "Abafado", ex: "O ar está muito abafado.", en: "Stuffy/Muggy" },
      { word: "Ventoinha", ex: "Liga a ventoinha.", en: "Fan" },
      { word: "Tromba d'água", ex: "Caiu uma tromba d'água.", en: "Cloudburst" },
      { word: "Céu", ex: "O céu está azul.", en: "Sky" }
    ]
  },
  {
    id: "greetings",
    title: "Greetings & Small Talk",
    portugueseTitle: "Cumprimentos",
    icon: "🤝",
    phrases: [{ pt: "Olá, tudo bem?", en: "Hello, is everything well?" }],
    roleplay: "Meeting a new person and starting a basic conversation.",
    keywords: [
      { word: "Olá", en: "Hello", ex: "Olá! Como estás?" },
      { word: "Bom dia", en: "Good morning", ex: "Bom dia a todos!" },
      { word: "Boa tarde", en: "Good afternoon", ex: "Boa tarde, senhor Silva." },
      { word: "Boa noite", en: "Good night/evening", ex: "Boa noite e bons sonhos." },
      { word: "Como estás?", en: "How are you?", ex: "Olá, como estás hoje?" },
      { word: "Tudo bem?", en: "Is everything ok?", ex: "Tudo bem por aqui." },
      { word: "Prazer", en: "Pleasure", ex: "Muito prazer em conhecer-te." },
      { word: "Até logo", en: "See you later", ex: "Tenho de ir, até logo!" },
      { word: "Tchau", en: "Bye", ex: "Tchau! Vemo-nos amanhã." },
      { word: "Adeus", en: "Goodbye", ex: "Adeus e boa viagem." },
      { word: "Obrigado", en: "Thank you (m)", ex: "Muito obrigado pela ajuda." },
      { word: "De nada", en: "You're welcome", ex: "De nada, foi um prazer." },
      { word: "Desculpa", en: "Sorry", ex: "Desculpa o atraso." },
      { word: "Com licença", en: "Excuse me", ex: "Com licença, posso passar?" },
      { word: "Por favor", en: "Please", ex: "Um café, por favor." },
      { word: "Chamo-me", en: "My name is", ex: "Chamo-me Pedro, e tu?" },
      { word: "Nome", en: "Name", ex: "Qual é o teu nome?" },
      { word: "Sou de", en: "I am from", ex: "Sou de Portugal." },
      { word: "Onde vives?", en: "Where do you live?", ex: "Onde vives agora?" },
      { word: "Quantos anos?", en: "How many years?", ex: "Quantos anos tens?" },
      { word: "Trabalho", en: "Work/Job", ex: "Onde é o teu trabalho?" },
      { word: "Estudo", en: "Study", ex: "Eu estudo português." },
      { word: "Sim", en: "Yes", ex: "Sim, eu quero ir." },
      { word: "Não", en: "No", ex: "Não, obrigado." },
      { word: "Talvez", en: "Maybe", ex: "Talvez eu vá amanhã." },
      { word: "Percebo", en: "I understand", ex: "Sim, eu percebo bem." },
      { word: "Repetir", en: "Repeat", ex: "Podes repetir, por favor?" },
      { word: "Devagar", en: "Slowly", ex: "Fala mais devagar." },
      { word: "Ajuda", en: "Help", ex: "Preciso de ajuda aqui." },
      { word: "Amigo", en: "Friend", ex: "Ele é o meu melhor amigo." }
    ]
  },
  {
    id: "connectors",
    title: "Connecting Words",
    portugueseTitle: "Conectores",
    icon: "🔗",
    phrases: [{ pt: "Eu falo português e inglês.", en: "I speak Portuguese and English." }],
    roleplay: "Linking ideas to make your sentences flow more naturally.",
    keywords: [
      { word: "E", en: "And", ex: "Gosto de café e chá." },
      { word: "Mas", en: "But", ex: "Quero ir, mas não posso." },
      { word: "Ou", en: "Or", ex: "Queres isto ou aquilo?" },
      { word: "Porque", en: "Because", ex: "Estudo porque gosto." },
      { word: "Por isso", en: "Therefore", ex: "Estava frio, por isso fiquei." },
      { word: "Também", en: "Also/Too", ex: "Eu também quero ir." },
      { word: "Embora", en: "Although", ex: "Vou, embora esteja cansado." },
      { word: "Apesar de", en: "Despite", ex: "Saímos apesar da chuva." },
      { word: "Se", en: "If", ex: "Se chover, não vou." },
      { word: "Quando", en: "When", ex: "Diz-me quando chegares." },
      { word: "Enquanto", en: "While", ex: "Lê enquanto esperas." },
      { word: "Antes de", en: "Before", ex: "Lava as mãos antes de comer." },
      { word: "Depois de", en: "After", ex: "Vou jantar depois de correr." },
      { word: "Durante", en: "During", ex: "Dormi durante o filme." },
      { word: "Além disso", en: "Besides", ex: "É barato, além disso é bom." },
      { word: "Então", en: "Then/So", ex: "Então, o que decidiste?" },
      { word: "Portanto", en: "So/Thus", ex: "Estudei, portanto passei." },
      { word: "Contudo", en: "However", ex: "Tentou, contudo falhou." },
      { word: "Todavia", en: "Nevertheless", ex: "É difícil, todavia possível." },
      { word: "Pois", en: "For/Because", ex: "Não fui, pois estava doente." },
      { word: "Assim", en: "Like this/So", ex: "Faz assim, com cuidado." },
      { word: "Caso", en: "In case", ex: "Leva o casaco, caso faça frio." },
      { word: "Já que", en: "Since", ex: "Já que estás aqui, ajuda-me." },
      { word: "Para que", en: "So that", ex: "Falei alto para que ouvissem." },
      { word: "Ainda que", en: "Even though", ex: "Vou, ainda que seja tarde." },
      { word: "Até", en: "Until/Even", ex: "Fico aqui até às cinco." },
      { word: "Exceto", en: "Except", ex: "Todos foram, exceto o João." },
      { word: "Salvo", en: "Save/Except", ex: "Está tudo bem, salvo a TV." },
      { word: "Contanto que", en: "Provided that", ex: "Vou, contanto que pagues." },
      { word: "Afinal", en: "After all", ex: "Afinal, eu tinha razão." }
    ]
  },
  {
    id: "alphabet",
    title: "Alphabet & Accents",
    portugueseTitle: "O Alfabeto",
    icon: "🔤",
    phrases: [{ pt: "Como se soletra o teu nome?", en: "How do you spell your name?" }],
    roleplay: "Practicing the unique sounds and accents of European Portuguese.",
    keywords: [
      { word: "A", en: "Letter A", ex: "Amigo começa com A." },
      { word: "B", en: "Letter B", ex: "B de bola." },
      { word: "C", en: "Letter C", ex: "Casa escreve-se com C." },
      { word: "Ç", en: "Cedilha", ex: "Maçã tem uma cedilha." },
      { word: "Á", en: "Agudo", ex: "Água tem acento agudo." },
      { word: "À", en: "Grave", ex: "Vou à escola." },
      { word: "Â", en: "Circunflexo", ex: "Lâmpada tem circunflexo." },
      { word: "Ã", en: "Til (Nasal)", ex: "Cão termina em til." },
      { word: "D", en: "Letter D", ex: "D de dado." },
      { word: "E", en: "Letter E", ex: "Escola com E." },
      { word: "F", en: "Letter F", ex: "F de faca." },
      { word: "G", en: "Letter G", ex: "G de gato." },
      { word: "H", en: "Letter H (Silent)", ex: "H de hoje." },
      { word: "I", en: "Letter I", ex: "I de ilha." },
      { word: "J", en: "Letter J", ex: "J de janela." },
      { word: "K", en: "Letter K", ex: "K de kilo." },
      { word: "L", en: "Letter L", ex: "L de livro." },
      { word: "M", en: "Letter M", ex: "M de mar." },
      { word: "N", en: "Letter N", ex: "N de navio." },
      { word: "O", en: "Letter O", ex: "O de ovo." },
      { word: "P", en: "Letter P", ex: "P de pai." },
      { word: "Q", en: "Letter Q", ex: "Q de queijo." },
      { word: "R", en: "Letter R", ex: "R de rato." },
      { word: "S", en: "Letter S", ex: "S de sol." },
      { word: "T", en: "Letter T", ex: "T de terra." },
      { word: "U", en: "Letter U", ex: "U de uva." },
      { word: "V", en: "Letter V", ex: "V de vento." },
      { word: "W", en: "Letter W", ex: "W de web." },
      { word: "X", en: "Letter X", ex: "X de xícara." },
      { word: "Z", en: "Letter Z", ex: "Z de zebra." }
    ]
  },
  {
    id: "questions",
    title: "Who, What, Where?",
    portugueseTitle: "Interrogações",
    icon: "❓",
    phrases: [{ pt: "Onde fica a estação?", en: "Where is the station?" }],
    roleplay: "Asking questions to find information and navigate daily life.",
    keywords: [
      { word: "Quem", en: "Who", ex: "Quem é aquela senhora?" },
      { word: "O quê", en: "What", ex: "O que é que disseste?" },
      { word: "Quando", en: "When", ex: "Quando é o teu jantar?" },
      { word: "Onde", en: "Where", ex: "Onde está a chave?" },
      { word: "Porque", en: "Why", ex: "Porque estás triste?" },
      { word: "Como", en: "How", ex: "Como se diz isto?" },
      { word: "Qual", en: "Which", ex: "Qual é o teu favorito?" },
      { word: "Quanto", en: "How much", ex: "Quanto custa o bilhete?" },
      { word: "Quantos", en: "How many", ex: "Quantos livros leste?" },
      { word: "Porquê", en: "Why (alone)", ex: "Não sei porquê." },
      { word: "Aonde", en: "Whereto", ex: "Aonde vais agora?" },
      { word: "De onde", en: "Wherefrom", ex: "De onde vens?" },
      { word: "De quem", en: "Whose", ex: "De quem é este carro?" },
      { word: "Com quem", en: "With whom", ex: "Com quem vais sair?" },
      { word: "Para quem", en: "For whom", ex: "Para quem é o presente?" },
      { word: "Para onde", en: "Towhere", ex: "Para onde olhas?" },
      { word: "A que horas", en: "At what time", ex: "A que horas começa?" },
      { word: "Com frequência", en: "How often", ex: "Com que frequência corres?" },
      { word: "Que tipo", en: "What type", ex: "Que tipo de música gostas?" },
      { word: "Qual deles", en: "Which of them", ex: "Qual deles queres?" },
      { word: "De que maneira", en: "In what way", ex: "De que maneira fizeste?" },
      { word: "Desde quando", en: "Since when", ex: "Desde quando estás aqui?" },
      { word: "Até quando", en: "Until when", ex: "Ficas até quando?" },
      { word: "Há quanto tempo", en: "For how long", ex: "Há quanto tempo esperas?" },
      { word: "Distância", en: "Distance", ex: "A que distância fica o café?" },
      { word: "Sobre o quê", en: "About what", ex: "Sobre o que falavam?" },
      { word: "Com quê", en: "With what", ex: "Com que abriste a porta?" },
      { word: "Dúvida", en: "Doubt", ex: "Tens alguma dúvida?" },
      { word: "Resposta", en: "Answer", ex: "Não sei a resposta." },
      { word: "Pergunta", en: "Question", ex: "Fiz uma pergunta difícil." }
    ]
  },
  {
    id: "directions",
    title: "Directions",
    portugueseTitle: "Direções",
    icon: "🗺️",
    phrases: [{ pt: "Vire à esquerda no semáforo.", en: "Turn left at the traffic light." }],
    roleplay: "Navigating through the streets of a Portuguese city.",
    keywords: [
      { word: "Esquerda", en: "Left", ex: "Vira à esquerda." },
      { word: "Direita", en: "Right", ex: "Fica à tua direita." },
      { word: "Em frente", en: "Straight ahead", ex: "Segue sempre em frente." },
      { word: "Atrás", en: "Behind", ex: "O carro está atrás." },
      { word: "Ao lado de", en: "Next to", ex: "Moro ao lado da escola." },
      { word: "Entre", en: "Between", ex: "Fica entre o banco e o café." },
      { word: "Esquina", en: "Corner", ex: "Vemo-nos na esquina." },
      { word: "Rua", en: "Street", ex: "Esta rua é muito estreita." },
      { word: "Avenida", en: "Avenue", ex: "A avenida é larga." },
      { word: "Praça", en: "Square", ex: "A praça central é linda." },
      { word: "Ponte", en: "Bridge", ex: "Atravessa a ponte." },
      { word: "Rotunda", en: "Roundabout", ex: "Sai na terceira saída." },
      { word: "Semáforo", en: "Traffic light", ex: "Para no semáforo." },
      { word: "Passadeira", en: "Crosswalk", ex: "Atravessa na passadeira." },
      { word: "Mapa", en: "Map", ex: "Estou a olhar para o mapa." },
      { word: "GPS", en: "GPS", ex: "O GPS diz para virar." },
      { word: "Norte", en: "North", ex: "O Porto fica no norte." },
      { word: "Sul", en: "South", ex: "O Algarve fica no sul." },
      { word: "Perto", en: "Near", ex: "Fica muito perto daqui." },
      { word: "Longe", en: "Far", ex: "A praia está longe." },
      { word: "Subir", en: "To go up", ex: "Tens de subir a colina." },
      { word: "Descer", en: "To go down", ex: "Desce as escadas." },
      { word: "Virar", en: "To turn", ex: "Vira na próxima rua." },
      { word: "Atravessar", en: "To cross", ex: "Atravessa o rio." },
      { word: "Localizar", en: "To locate", ex: "Não consigo localizar a loja." },
      { word: "Sinal", en: "Sign", ex: "Segue o sinal de trânsito." },
      { word: "Distância", en: "Distance", ex: "A distância é curta." },
      { word: "Chegar", en: "To arrive", ex: "Quero chegar depressa." },
      { word: "Partir", en: "To leave", ex: "O comboio vai partir." },
      { word: "Destino", en: "Destination", ex: "Qual é o teu destino?" }
    ]
  },
  {
    id: "prepositions",
    title: "Prepositions",
    portugueseTitle: "Preposições",
    icon: "📍",
    phrases: [{ pt: "O gato está debaixo da mesa.", en: "The cat is under the table." }],
    roleplay: "Defining where objects are located in space.",
    keywords: [
      { word: "On", en: "Em cima de", ex: "O livro está em cima de mesa." },
      { word: "Under", en: "Debaixo de", ex: "As chaves caíram debaixo do sofá." },
      { word: "In", en: "Dentro de", ex: "O leite está dentro do frigorífico." },
      { word: "Out", en: "Fora de", ex: "Ela está fora de casa." },
      { word: "Front", en: "À frente de", ex: "Espera-me à frente do cinema." },
      { word: "Behind", en: "Atrás de", ex: "O jardim fica atrás da casa." },
      { word: "Near", en: "Perto de", ex: "Moro perto de ti." },
      { word: "Far", en: "Longe de", ex: "A cidade está longe de mar." },
      { word: "Between", en: "Entre", ex: "Senta-te entre nós." },
      { word: "Beside", en: "Ao lado de", ex: "Fica ao lado do banco." },
      { word: "Over", en: "Por cima de", ex: "O avião voa por cima de nuvens." },
      { word: "Below", en: "Por baixo de", ex: "O peixe nada por baixo de água." },
      { word: "Through", en: "Através de", ex: "Olha através da janela." },
      { word: "Against", en: "Contra", ex: "Encosta-te contra a parede." },
      { word: "Without", en: "Sem", ex: "Não vivo sem café." },
      { word: "With", en: "Com", ex: "Vou com os meus amigos." },
      { word: "To", en: "Para / A", ex: "Este presente é para ti." },
      { word: "By/For", en: "Por", ex: "Vou por aquele caminho." },
      { word: "Of/From", en: "De", ex: "Sou de Lisboa." },
      { word: "At/In", en: "Em", ex: "Estou em casa." },
      { word: "Since", en: "Desde", ex: "Trabalho desde as oito." },
      { word: "Until", en: "Até", ex: "Até amanhã!" },
      { word: "Past", en: "Depois de / Passado", ex: "Passou por mim." },
      { word: "Across", en: "Do outro lado", ex: "Moro do outro lado da rua." },
      { word: "Towards", en: "Em direção a", ex: "Caminha em direção à luz." },
      { word: "Among", en: "Entre (muitos)", ex: "Ele estava entre a multidão." },
      { word: "Above", en: "Acima de", ex: "Fica acima das expectativas." },
      { word: "Before", en: "Perante", ex: "Compareceu perante o juiz." },
      { word: "According to", en: "Segundo", ex: "Segundo as notícias, vai chover." },
      { word: "Under (Abstract)", en: "Sob", ex: "Estamos sob pressão." }
    ]
  },
  {
    id: "phrases",
    title: "Useful Phrases",
    portugueseTitle: "Expressões",
    icon: "✨",
    phrases: [{ pt: "É verdade, concordo contigo.", en: "It's true, I agree with you." }],
    roleplay: "Common idiomatic expressions to sound like a local.",
    keywords: [
      { word: "Claro", en: "Of course", ex: "Claro que sim!" },
      { word: "Certeza", en: "Certainty", ex: "Tens a certeza?" },
      { word: "Acho que", en: "I think that", ex: "Acho que vai chover." },
      { word: "Pois é", en: "Indeed/That's right", ex: "Pois é, tens razão." },
      { word: "Verdade", en: "True/Truth", ex: "É verdade, fui eu." },
      { word: "Exato", en: "Exactly", ex: "Exatamente o que eu disse." },
      { word: "Pelos vistos", en: "Apparently", ex: "Pelos vistos, ele ganhou." },
      { word: "Quem sabe?", en: "Who knows?", ex: "Talvez sim, quem sabe?" },
      { word: "Oxalá!", en: "Hopefully!", ex: "Oxalá que corra tudo bem." },
      { word: "Paciência", en: "Patience / Oh well", ex: "É preciso ter paciência." },
      { word: "Não faz mal", en: "It doesn't matter", ex: "Não faz mal, eu ajudo." },
      { word: "Chatice", en: "Bummer/Nuisance", ex: "Que chatice, perdi o autocarro." },
      { word: "Fixe", en: "Cool", ex: "Este sítio é bué da fixe!" },
      { word: "A sério?", en: "Seriously?", ex: "Ganhaste? A sério?" },
      { word: "Já agora", en: "By the way", ex: "Já agora, como se chama?" },
      { word: "No fundo", en: "Deep down", ex: "No fundo, ele é bom." },
      { word: "Afinal", en: "After all", ex: "Afinal, chegaste a horas." },
      { word: "Mesmo", en: "Even/Really", ex: "A sério? Mesmo?" },
      { word: "Pois", en: "Yeah/Right", ex: "Pois, eu compreendo." },
      { word: "Olhe lá", en: "Look here/Pardon", ex: "Olhe lá, pode ajudar-me?" },
      { word: "Gozar", en: "To joke/mock", ex: "Estás a gozar comigo?" },
      { word: "Tomara!", en: "I wish/hope so!", ex: "Tomara que ganhemos." },
      { word: "Visto que", en: "Given that", ex: "Visto que é tarde, vou-me embora." },
      { word: "De qualquer forma", en: "Anyway", ex: "Vou de qualquer forma." },
      { word: "Enfim", en: "In short / Oh well", ex: "Enfim, terminou o dia." },
      { word: "Ainda bem", en: "Good thing/Gladly", ex: "Ainda bem que vieste." },
      { word: "Dá cá", en: "Give it here", ex: "Dá cá esse livro." },
      { word: "Deixa lá", en: "Never mind", ex: "Deixa lá, não te preocupes." },
      { word: "Vá lá", en: "Come on", ex: "Vá lá, ajuda os teus amigos." },
      { word: "Olha", en: "Look", ex: "Olha para aquele castelo." }
    ]
  },
  {
    id: "family",
    title: "Family",
    portugueseTitle: "A Família",
    icon: "👨‍👩‍👧‍👦",
    phrases: [{ pt: "A minha mãe é portuguesa.", en: "My mother is Portuguese." }],
    roleplay: "Talking about your relatives and family history.",
    keywords: [
      { word: "Mãe", en: "Mother", ex: "A minha mãe é médica." },
      { word: "Pai", en: "Father", ex: "O meu pai gosta de cozinhar." },
      { word: "Irmão", en: "Brother", ex: "O meu irmão viaja muito." },
      { word: "Irmã", en: "Sister", ex: "A minha irmã estuda artes." },
      { word: "Avó", en: "Grandmother", ex: "A minha avó faz bolos." },
      { word: "Avô", en: "Grandfather", ex: "O meu avô conta histórias." },
      { word: "Filho", en: "Son", ex: "O meu filho tem cinco anos." },
      { word: "Filha", en: "Daughter", ex: "A minha filha joga ténis." },
      { word: "Tio", en: "Uncle", ex: "O meu tio vive no Algarve." },
      { word: "Tia", en: "Aunt", ex: "A minha tia é professora." },
      { word: "Primo", en: "Cousin (m)", ex: "O meu primo vem jantar." },
      { word: "Prima", en: "Cousin (f)", ex: "A minha prima é simpática." },
      { word: "Neto", en: "Grandson", ex: "O meu neto é muito alto." },
      { word: "Marido", en: "Husband", ex: "O meu marido está no trabalho." },
      { word: "Esposa", en: "Wife", ex: "A minha esposa fala inglês." },
      { word: "Sogro", en: "Father-in-law", ex: "O meu sogro é reformado." },
      { word: "Nora", en: "Daughter-in-law", ex: "A minha nora é advogada." },
      { word: "Gémeos", en: "Twins", ex: "Eles são gémeos." },
      { word: "Bebé", en: "Baby", ex: "O bebé está a dormir." },
      { word: "Criança", en: "Child", ex: "A criança está a brincar." }
    ]
  },
  {
    id: "diy-store",
    title: "At the DIY Store",
    portugueseTitle: "No Aki / Leroy Merlin",
    icon: "🛠️",
    phrases: [{ pt: "Onde estão os parafusos?", en: "Where are the screws?" }],
    roleplay: "Asking for tools at a Portuguese home improvement store.",
    keywords: [
      { word: "Martelo", en: "Hammer", ex: "Onde está o martelo?" },
      { word: "Prego", en: "Nail", ex: "Preciso de um prego." },
      { word: "Serra", en: "Saw", ex: "Esta serra é muito afiada." },
      { word: "Parafuso", en: "Screw", ex: "O parafuso está solto." },
      { word: "Berbequim", en: "Drill", ex: "O berbequim faz barulho." },
      { word: "Tinta", en: "Paint", ex: "Escolhi a tinta branca." },
      { word: "Pincel", en: "Brush", ex: "Lava o pincel depois de usar." },
      { word: "Madeira", en: "Wood", ex: "Esta madeira é de carvalho." },
      { word: "Cano", en: "Pipe", ex: "O cano está entupido." },
      { word: "Lâmpada", en: "Bulb", ex: "A lâmpada fundiu." }
    ]
  },
  {
    id: "hobbies",
    title: "Hobbies",
    portugueseTitle: "Passatempos",
    icon: "🎸",
    phrases: [{ pt: "Gosto de tocar guitarra.", en: "I like to play guitar." }],
    roleplay: "Discussing what you do for fun in your leisure time.",
    keywords: [
      { word: "Musica", en: "Music", ex: "Eu oiço música relaxante." },
      { word: "Leitura", en: "Reading", ex: "A leitura abre horizontes." },
      { word: "Viagem", en: "Travel", ex: "Uma viagem inesquecível." },
      { word: "Cozinha", en: "Cooking", ex: "A cozinha é a minha paixão." },
      { word: "Fotografia", en: "Photography", ex: "Adoro tirar fotografias." },
      { word: "Corrida", en: "Running", ex: "A corrida dá-me energia." },
      { word: "Guitarra", en: "Guitar", ex: "A minha guitarra é nova." },
      { word: "Dança", en: "Dance", ex: "A dança é libertadora." },
      { word: "Yoga", en: "Yoga", ex: "O yoga traz paz." },
      { word: "Pesca", en: "Fishing", ex: "A pesca exige silêncio." }
    ]
  }
];
